export const INIT_MEMO_LISTS = 'INIT_MEMO_LISTS';
export const SEARCH_MEMO_LISTS = 'SEARCH_MEMO_LISTS';
export const UPDATE_MEMO_LISTS = 'UPDATE_MEMO_LISTS';

export const UPDATE_MEMO = 'UPDATE_MEMO';
export const DELETE_MEMO = 'DELETE_MEMO';

export const SET_CURRENT_ID = 'SET_CURRENT_ID';
export const SET_CURRENT_TEXT = 'SET_CURRENT_TEXT';
export const SET_CURRENT_SEARCH_WORD = 'SET_CURRENT_SEARCH_WORD';
export const CLEAR_CURRENT_SEARCH_WORD = 'CLEAR_CURRENT_SEARCH_WORD';
