export const INIT_MEMO_LISTS = 'INIT_MEMO_LISTS';
export const UPDATE_MEMO_LISTS = 'UPDATE_MEMO_LISTS';
export const SET_CURRENT_ID = 'SET_CURRENT_ID';
export const SET_CURRENT_TEXT = 'SET_CURRENT_TEXT';
export const UPDATE_MEMO = 'UPDATE_MEMO';
